name: List Available macOS Releases

on:
  workflow_dispatch:

jobs:
  list-installers:
    runs-on: macos-latest
    outputs:
      list: ${{ steps.list.outputs.list }}
    steps:
      - uses: actions/checkout@v3
      - id: list
        name: List Installers
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate
          softwareupdate --list-full-installers
          echo "list=softwareupdate --list-full-installers" >> "$GITHUB_OUTPUT"
  re-run-failed-jobs:
    runs-on: ubuntu-latest
    needs: [list-installers]
    if: always() && (needs.list-installers.result == 'failure')
    steps:
      - name: Needs Context
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: echo "$NEEDS_CONTEXT"
